# Библиотека Numpy

In [1]:
import numpy as np

### Создание и заполнение массивов

**np.array** - создание нового массива. Обязательным аргументом на входе должен быть список или кортеж значений, которые передаются в массив. 
Из часто используемых аргументов ***dtype*** - устанавливает тип данных в массиве. 
Все элементы массива обязательно должны иметь одинаковый тип данных.

In [4]:
np.array([1,2,3,4,5], dtype = np.float32)

array([1., 2., 3., 4., 5.], dtype=float32)

Список поддерживаемых типов: 

In [2]:
np.sctypeDict

{'?': numpy.bool_,
 0: numpy.bool_,
 'byte': numpy.int8,
 'b': numpy.int8,
 1: numpy.int8,
 'ubyte': numpy.uint8,
 'B': numpy.uint8,
 2: numpy.uint8,
 'short': numpy.int16,
 'h': numpy.int16,
 3: numpy.int16,
 'ushort': numpy.uint16,
 'H': numpy.uint16,
 4: numpy.uint16,
 'i': numpy.intc,
 5: numpy.intc,
 'uint': numpy.uint32,
 'I': numpy.uintc,
 6: numpy.uintc,
 'intp': numpy.int64,
 'p': numpy.int64,
 9: numpy.int64,
 'uintp': numpy.uint64,
 'P': numpy.uint64,
 10: numpy.uint64,
 'long': numpy.int32,
 'l': numpy.int32,
 7: numpy.int32,
 'ulong': numpy.uint32,
 'L': numpy.uint32,
 8: numpy.uint32,
 'longlong': numpy.int64,
 'q': numpy.int64,
 'ulonglong': numpy.uint64,
 'Q': numpy.uint64,
 'half': numpy.float16,
 'e': numpy.float16,
 23: numpy.float16,
 'f': numpy.float32,
 11: numpy.float32,
 'double': numpy.float64,
 'd': numpy.float64,
 12: numpy.float64,
 'longdouble': numpy.longdouble,
 'g': numpy.longdouble,
 13: numpy.longdouble,
 'cfloat': numpy.complex128,
 'F': numpy.complex

**np.array.ndim** - показывает количество измерений в массиве (осей). ndim = 1 для одномерного массива, 2 для двумерного и т.д.

In [9]:
print(f'Массив: [1,2,3,4,5] - ndim = {np.array([1,2,3,4,5]).ndim}')
print(f'Массив: [[1,2,3,4,5], [1,2,3,4,5]] - ndim = {np.array([[1,2,3,4,5], [1,2,3,4,5]]).ndim}')
print(f'Массив: [[[1,2,3,4,5], [1,2,3,4,5], [1,2,3,4,5]]] - ndim = {np.array([[[1,2,3,4,5], [1,2,3,4,5], [1,2,3,4,5]]]).ndim}')

Массив: [1,2,3,4,5] - ndim = 1
Массив: [[1,2,3,4,5], [1,2,3,4,5]] - ndim = 2
Массив: [[[1,2,3,4,5], [1,2,3,4,5], [1,2,3,4,5]]] - ndim = 3


**np.array.shape** - показывает количество элементов в каждом измерении (на каждой оси). 

In [13]:
print(f'Массив: [1,2,3,4,5] - shape = {np.array([1,2,3,4,5]).shape}')
print(f'Массив: [[1,2,3,4,5], [1,2,3,4,5]] - shape = {np.array([[1,2,3,4,5], [1,2,3,4,5]]).shape}')
print(f'Массив: [[[1,2,3,4,5], [1,2,3,4,5], [1,2,3,4,5]]] - shape = {np.array([[[1,2,3,4,5], [1,2,3,4,5], [1,2,3,4,5]]]).shape}')

Массив: [1,2,3,4,5] - shape = (5,)
Массив: [[1,2,3,4,5], [1,2,3,4,5]] - shape = (2, 5)
Массив: [[[1,2,3,4,5], [1,2,3,4,5], [1,2,3,4,5]]] - shape = (1, 3, 5)


**np.array.size** - количество элементов во всём массиве. 

In [15]:
print(f'Массив: [1,2,3,4,5] - size = {np.array([1,2,3,4,5]).size}')
print(f'Массив: [[1,2,3,4,5], [1,2,3,4,5]] - size = {np.array([[1,2,3,4,5], [1,2,3,4,5]]).size}')
print(f'Массив: [[[1,2,3,4,5], [1,2,3,4,5], [1,2,3,4,5]]] - size = {np.array([[[1,2,3,4,5], [1,2,3,4,5], [1,2,3,4,5]]]).size}')

Массив: [1,2,3,4,5] - size = 5
Массив: [[1,2,3,4,5], [1,2,3,4,5]] - size = 10
Массив: [[[1,2,3,4,5], [1,2,3,4,5], [1,2,3,4,5]]] - size = 15


Вектор (одномерный массив) и вектор-столбец или вектор-строка (двумерные массивы) **являются различными объектами в NumPy**, хотя математически задают один и тот же объект. В случае одномерного массива кортеж shape состоит из одного числа и имеет вид (n,), где n — длина вектора. В случае двумерных векторов в shape присутствует еще одна размерность, равная единице.

Свойство **shape** массива можно перезаписать, тогда представление исходного массива изменится. При этом важно, чтобы произведение значений в кортеже ***shape*** было равно произведению исходных значений. Это даст возможность не потерять данные. 

In [33]:
dim_1 = np.array([1,2,3,4,5])
dim_2 = np.array([[1,2,3,4,5], [1,2,3,4,5]])
dim_3 = np.array([[[1,2,3,4,5], [1,2,3,4,5], [1,2,3,4,5]]])

dim_1.shape = (5,1)
print('Массив: [1,2,3,4,5], устанавливаем shape = (5,1), получаем:')
print(dim_1)

print('----')
print('Массив: [1,2,3,4,5], устанавливаем shape = (1,5), получаем:')
dim_1.shape = (1,5)
print(dim_1)

print('----')
print('Массив: [[1,2,3,4,5], [1,2,3,4,5]], устанавливаем shape = (5,2), получаем:')
dim_2.shape = (5,2)
print(dim_2)

print('----')
print('Массив: [[1,2,3,4,5], [1,2,3,4,5]], устанавливаем shape = (5,2,1), получаем:')
dim_2.shape = (5,2,1)
print(dim_2)

print('----')
print('Массив: [[[1,2,3,4,5], [1,2,3,4,5], [1,2,3,4,5]]], устанавливаем shape = -1, получаем:')
dim_3.shape = -1
print(dim_3)

Массив: [1,2,3,4,5], устанавливаем shape = (5,1), получаем:
[[1]
 [2]
 [3]
 [4]
 [5]]
----
Массив: [1,2,3,4,5], устанавливаем shape = (1,5), получаем:
[[1 2 3 4 5]]
----
Массив: [[1,2,3,4,5], [1,2,3,4,5]], устанавливаем shape = (5,2), получаем:
[[1 2]
 [3 4]
 [5 1]
 [2 3]
 [4 5]]
----
Массив: [[1,2,3,4,5], [1,2,3,4,5]], устанавливаем shape = (5,2,1), получаем:
[[[1]
  [2]]

 [[3]
  [4]]

 [[5]
  [1]]

 [[2]
  [3]]

 [[4]
  [5]]]
----
Массив: [[[1,2,3,4,5], [1,2,3,4,5], [1,2,3,4,5]]], устанавливаем shape = -1, получаем:
[1 2 3 4 5 1 2 3 4 5 1 2 3 4 5]


**np.empty** - новый массив с произвольными значениями. Значения элементов массива будут зависеть от текущего состояния памяти. Функция оптимизирована для быстродействия, поэтому фактически этот метод стоит применять только для создания массивов, которые будут перезаписываться. 

In [34]:
np.empty(10)

array([1.57525147e-311, 2.32210854e-322, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 1.16095484e-028, 3.65093134e+233, 4.25117084e-096,
       9.80058441e+252, 1.23971686e+224])

In [39]:
np.empty(10, dtype = np.int32)

array([         0,          0, 1479177968,        742, 1479176880,
              742, 1479176944,        742,    7209065,          0])

**np.arange** - создаёт массив из последовательных чисел от и до заданного, не включая его. Работает аналогично ***range*** в python, но позволяет оперировать с дробными значениями. 

In [40]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
np.arange(1, 10, 0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

In [42]:
np.arange(1.2, 3, 0.2)

array([1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4, 2.6, 2.8])

In [44]:
np.arange(1.2, 3.1, 0.4)

array([1.2, 1.6, 2. , 2.4, 2.8])

**np.linspace** - создаёт массив с равномерно распределёнными значениями в заданном интервале. Принимает началльное значение последовательности, конечное, и число элементов. Если указать аргумент ***retstep = True***, то функция вернёт значение шага.

In [3]:
np.linspace(0, 10, 50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [4]:
np.linspace(0, 1, 5, retstep = True)

(array([0.  , 0.25, 0.5 , 0.75, 1.  ]), 0.25)

**np.ones** - создаёт массив с единицами. 

In [48]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [47]:
np.ones([5,2])

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

**np.ones_like** - создаёт массив размера, аналогичного тому, который на входе, но содержащего только единицы.

In [50]:
np.ones_like(np.array([1,2,3,4,5]))

array([1, 1, 1, 1, 1])

In [51]:
np.ones_like(np.array([[1,2,3,4,5], [1,2,3,4,5]]))

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

**np.zeros** - создаёт массив с нулями. 

In [52]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [53]:
np.zeros([5,2])

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

**np.ones_like** - создаёт массив размера, аналогичного тому, который на входе, но содержащего только нули.

In [56]:
np.zeros_like(np.array([1,2,3,4,5]))

array([0, 0, 0, 0, 0])

In [54]:
np.zeros_like(np.array([[1,2,3,4,5], [1,2,3,4,5]]))

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

**np.full** - создаёт массив, заполненный заданным значением. Первым аргументом передаётся размер массива, вторым - значение, которым необходимо заполнить массив. 

In [58]:
np.full(5, 10)

array([10, 10, 10, 10, 10])

In [59]:
np.full([5,2], 10)

array([[10, 10],
       [10, 10],
       [10, 10],
       [10, 10],
       [10, 10]])

**np.full_like** - создаёт массив размера, аналогичного тому, который на входе, но содержащего только заданные значения. 

In [61]:
np.full_like(np.array([1,2,3,4,5]), 10)

array([10, 10, 10, 10, 10])

In [62]:
np.full_like(np.array([[1,2,3,4,5], [1,2,3,4,5]]), 10)

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

**np.mat** - создаёт матрицу на основе данных строки, списка или кортежа, преобразуя эти объекты необходимым образом, чтобы получить матрицу (но это не всегда возможно).

In [9]:
display(np.mat('1 2 3 4')) # создает матрицу 1x4 из строки
display(np.mat('1, 2, 3, 4')) # то же самое: создает матрицу 1x4 из строки
display(np.mat('1 2; 3 4')) # возвращает матрицу 2x2

matrix([[1, 2, 3, 4]])

matrix([[1, 2, 3, 4]])

matrix([[1, 2],
        [3, 4]])

**np.tile** - создаёт массив на основе повторения элементов. Первым аргументом принимает массив, который необходимо дублировать, вторым - количество раз, которое его нужно повторить. Второй аргумент может задаваться в виде кортежа, который определяет финальный вид созданного массива: каждый элемент в кортеже отвечает за то, сколько раз исходный массив продублировать вдоль соответствующей оси.

In [7]:
np.tile(np.array([1,2,3,4,5]), 10)

array([1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2,
       3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4,
       5, 1, 2, 3, 4, 5])

In [5]:
np.tile(np.array([1,2,3,4,5]), (2,2))

array([[1, 2, 3, 4, 5, 1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]])

In [9]:
np.tile(np.array([1,2,3,4,5]), (2,2,2))

array([[[1, 2, 3, 4, 5, 1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]],

       [[1, 2, 3, 4, 5, 1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]]])

### Создание и заполнение матриц

**np.asmatrix** - создание матрицы на основе заданного списка / кортежа.

In [68]:
np.asmatrix([(1,2,3), (1,2,3), (1,2,3)])

matrix([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]])

**np.diag** - создаёт матрицу с элементами на главной диагонали из заданного списка и нулями вне главной диагонали. Если в функцию передаётся не список, а массив, то будут возвращены значения, лежащие на главной диагонали этого массива.

In [69]:
np.diag([1,2,3,4,5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [72]:
np.diag(np.array([[1,2,3,4,5], [1,2,3,4,5], [1,2,3,4,5]]))

array([1, 2, 3])

**np.diagflat** - создаёт матрицу с элементами на главной диагонали из переданного массива. Похожа на ***np.diag***, но если ***np.diag*** обрабатывает только переданный массив, но ***diagflat*** сначала извлекает все значения из него, а затем строит матрицу. Результаты между ними будут отличаться в случае многомерных массивов. 

In [73]:
np.diagflat([1,2,3,4,5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [74]:
np.diagflat(np.array([[1,2,3,4,5], [1,2,3,4,5], [1,2,3,4,5]]))

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5]])

**np.eye** - создаёт матрицу с единицами на главной диагонали. Если передан один аргумент, то создаётся квадратная матрица этого размера. 
Если передано два неодинаковых аргумента, то создаётся матрица соответствующего размера с единицами на главной диагонали. Третий аргумент отвечает за смещение главной диагонали (по вертикали, если значение положительно и по горизонтали, если отрицательно). 

In [75]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [77]:
np.eye(5,10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]])

In [82]:
np.eye(5,10,2)

array([[0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.]])

In [83]:
np.eye(5,10,-2)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.]])

**np.identity** - оздаёт матрицу с единицами на главной диагонали. Работает аналогично ***np.eye*** с одним аргументом. 

In [86]:
np.identity(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

**np.tri** - создаёт нижнюю треугольную матрицу, состоящую из единиц ниже главной диагонали. Если передан один аргумент, то создаётся квадратная матрица этого размера. Если передано два неодинаковых аргумента, то создаётся матрица соответствующего размера с единицами на главной диагонали. Третий аргумент отвечает за смещение главной диагонали (по вертикали, если значение положительно и по горизонтали, если отрицательно). 

In [90]:
np.tri(5)

array([[1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 1.]])

In [91]:
np.tri(5,10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 0., 0., 0., 0., 0.]])

In [92]:
np.tri(5,10,2)

array([[1., 1., 1., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 0., 0., 0.]])

In [93]:
np.tri(5,10,-2)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0., 0., 0., 0., 0.]])

**np.tril** - создаёт нижнюю треугольную матрицу из переданного массива, обнуляя все значения выше главной диагонали. 
Принимает на вход как матрицу, так и массив или список. Если передать "не-квадратный" массив или список, то он будет сначала автоматически преобразован в двумерную матрицу и затем обработан.

In [99]:
np.tril(np.ones(5))

array([[1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 1.]])

In [100]:
np.tril([[1,2,3,4,5], [1,2,3,4,5]])

array([[1, 0, 0, 0, 0],
       [1, 2, 0, 0, 0]])

**np.triu** - аналогично ***np.tril***, но работает с верхней треугольной матрицей. 

### Представление массива

Массив - это набор элементов. 
Представление массива - это то, как эти элементы комбинируются между собой, распределяются по измерениям (осям) и представляются пользователю. 
Массив может иметь неограниченное количество представлений. 

При этом изменение исходного массива также меняет и все представления этого массива. 

**np.array.shape** - через данный метод можно менять представление массива, если присвоить ему значение или кортеж, соответствующий новому представлению. Одно число задаётся, если необходимо задать представление массива как одномерного. 
При этом это число должно быть равно свойству ***size***, либо -1. 

In [27]:
arr = np.array([[1,2,3,4,5], [1,2,3,4,5], [1,2,3,4,5]])
print(f'Исходное представление: \n{arr}')
arr.shape = 15
print(f'\nНовое представление: \n{arr}')

Исходное представление: 
[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]

Новое представление: 
[1 2 3 4 5 1 2 3 4 5 1 2 3 4 5]


Если же задаётся кортеж, то произведение значений в нём должно быть равно свойству ***size***. 
При этом расчёт требуемого числа для одной из осей можно упустить, поставив туда -1, тогда требуемое число будет рассчитано автоматически. 

In [34]:
arr = np.array([[1,2,3,4,5,6], [1,2,3,4,5,6], [1,2,3,4,5,6]])
print(f'Исходное представление: \n{arr}')
arr.shape = (2,9)
print(f'\nПредставление для shape = (2,9): \n{arr}')
arr.shape = (6,3)
print(f'\nПредставление для shape = (6,3): \n{arr}')
arr.shape = (9,2)
print(f'\nПредставление для shape = (9,2): \n{arr}')

Исходное представление: 
[[1 2 3 4 5 6]
 [1 2 3 4 5 6]
 [1 2 3 4 5 6]]

Представление для shape = (2,9): 
[[1 2 3 4 5 6 1 2 3]
 [4 5 6 1 2 3 4 5 6]]

Представление для shape = (6,3): 
[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]

Представление для shape = (9,2): 
[[1 2]
 [3 4]
 [5 6]
 [1 2]
 [3 4]
 [5 6]
 [1 2]
 [3 4]
 [5 6]]


**N.B.** Изменение представления "наоборот" (например, из (3,4) в (4,3)) не производит транспонирования. Все элементы сначала раскрываются в одну последовательность, из которой извлекается нужное число для помещения на ось.

**np.array.reshape** - создание нового представления массива. При этом не меняется представление исходного массива, в отличие от ***np.array.shape***.

In [40]:
arr = np.array([[1,2,3,4,5,6], [1,2,3,4,5,6], [1,2,3,4,5,6]])
print(f'Исходное представление: \n{arr}')
arr_reshape = arr.reshape(2,9)
print(f'\nНовое представление - (2,9): \n {arr_reshape}')
print(f'\nИсходное представление не меняется: \n{arr}')

Исходное представление: 
[[1 2 3 4 5 6]
 [1 2 3 4 5 6]
 [1 2 3 4 5 6]]

Новое представление - (2,9): 
 [[1 2 3 4 5 6 1 2 3]
 [4 5 6 1 2 3 4 5 6]]

Исходное представление не меняется: 
[[1 2 3 4 5 6]
 [1 2 3 4 5 6]
 [1 2 3 4 5 6]]


**np.array.resize** - расширенное изменение представления массива. Функционал схожий с изменением через ***np.array.shape***. 
Главное отличие - можно указывать значения так, чтобы размерность в новом представлении отличалась от размерности исходного (для этого указать аргумент ***refcheck = False***).

Недостающие элементы в новом представлении будут заменены нулями. Избыточные элементы не будут отображены. Количество элементов меняется, поэтому есть риск потери информации. 

Также метод не принимает -1 в качестве аргумента для упрощённого расчёта количества элементов на оси. 

In [56]:
arr = np.array([[1,2,3,4,5,6], [1,2,3,4,5,6], [1,2,3,4,5,6]])
print(f'Исходное представление: \n{arr}')
arr.resize(4,3)
print(f'\nНовое представление - (4,3): \n {arr}')
arr.resize(3,5)
print(f'\nНовое представление - (3,5): \n {arr}')

Исходное представление: 
[[1 2 3 4 5 6]
 [1 2 3 4 5 6]
 [1 2 3 4 5 6]]

Новое представление - (4,3): 
 [[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]

Новое представление - (3,5): 
 [[1 2 3 4 5]
 [6 1 2 3 4]
 [5 6 0 0 0]]


**np.array.ravel** - создание одномерного представления массива, без изменения текущего массива. 

In [52]:
arr = np.array([[1,2,3,4,5,6], [1,2,3,4,5,6], [1,2,3,4,5,6]])
arr.resize(4,4)
arr.ravel()

array([1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6, 1, 2, 3, 4])

**np.array.view** - создаёт копию представления массива. Дальнейшие изменения представления исходного массива не повлияют на результат, созданный данной функцией. 
На это представление влияет изменение данных в массиве, но не влияет изменение представления исходного массива. 

In [76]:
arr = np.array([[1,2,3,4,5,6], [1,2,3,4,5,6], [1,2,3,4,5,6]])
print(f'Исходное представление: \n{arr}')
arr_view = arr.view()
arr.resize(4,3, refcheck = False)
print(f'\nНовое представление - (4,3): \n {arr}')
print(f'\nСохранённое представление: \n {arr_view}')

Исходное представление: 
[[1 2 3 4 5 6]
 [1 2 3 4 5 6]
 [1 2 3 4 5 6]]

Новое представление - (4,3): 
 [[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]

Сохранённое представление: 
 [[1 2 3 4 5 6]
 [1 2 3 4 5 6]
 [1 2 3 4 5 6]]


При этом повторный запуск сохранённого представления отобразит массив той же размерности, но без сохранения значений. 

In [78]:
print(arr_view)

[[      0       0       0       0       0       0]
 [      0       0       0       0     972       0]
 [      0 4980828       0 7077985       0       6]]


**np.array.copy** - создаёт полную копию массива, включая данные и представление. 

In [80]:
arr = np.array([[1,2,3,4,5,6], [1,2,3,4,5,6], [1,2,3,4,5,6]])
print(f'Исходное представление: \n{arr}')
arr_copy = arr.copy()
arr.resize(4,3, refcheck = False)
print(f'\nНовое представление - (4,3): \n {arr}')
print(f'\nСохранённая копия: \n {arr_copy}')

Исходное представление: 
[[1 2 3 4 5 6]
 [1 2 3 4 5 6]
 [1 2 3 4 5 6]]

Новое представление - (4,3): 
 [[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]

Сохранённая копия: 
 [[1 2 3 4 5 6]
 [1 2 3 4 5 6]
 [1 2 3 4 5 6]]


In [83]:
print(f'Следующий запуск: \n{arr_copy}')

Следующий запуск: 
[[1 2 3 4 5 6]
 [1 2 3 4 5 6]
 [1 2 3 4 5 6]]


### Работа с измерениями (осями)

**np.expand_dims** - добавление нового измерения (оси). Функция принимает массив, и в аргументе axis указывается номер добавляемой оси. Функция возвращает новое представление массива. 

In [16]:
arr = np.array([[1,2,3,4,5,6], [1,2,3,4,5,6], [1,2,3,4,5,6]])
print(f'Исходное представление: \n{arr}')
print(f'\nПредставление после добавления оси на 3-е измерение:\n {np.expand_dims(arr, axis = 2)}')

Исходное представление: 
[[1 2 3 4 5 6]
 [1 2 3 4 5 6]
 [1 2 3 4 5 6]]

Представление после добавления оси на 3-е измерение:
 [[[1]
  [2]
  [3]
  [4]
  [5]
  [6]]

 [[1]
  [2]
  [3]
  [4]
  [5]
  [6]]

 [[1]
  [2]
  [3]
  [4]
  [5]
  [6]]]


**np.newaxis** - альтернативный метод добавления оси. В квадратных скобках к массиву можно написать ***np.newaxis***, чтобы добавить ось. Если массив многомерный, то в квадратный скобках через запятую пишется двоеточие там, где ось нужно сохранить, и np.newaxis - где нужно добавить. При большом количестве измерений - вместо двоеточия пишется троеточие. 

In [19]:
arr = np.array([[1,2,3,4,5,6], [1,2,3,4,5,6], [1,2,3,4,5,6]])
print(f'Исходное представление: \n{arr}')
print(f'\nПредставление после добавления оси на 1-е измерение:\n {arr[np.newaxis, :]}')
print(f'\nПредставление после добавления оси на 2-е измерение:\n {arr[:, np.newaxis]}')
print(f'\nПредставление после добавления оси на 3-е измерение:\n {arr[..., np.newaxis]}')

Исходное представление: 
[[1 2 3 4 5 6]
 [1 2 3 4 5 6]
 [1 2 3 4 5 6]]

Представление после добавления оси на 1-е измерение:
 [[[1 2 3 4 5 6]
  [1 2 3 4 5 6]
  [1 2 3 4 5 6]]]

Представление после добавления оси на 2-е измерение:
 [[[1 2 3 4 5 6]]

 [[1 2 3 4 5 6]]

 [[1 2 3 4 5 6]]]

Представление после добавления оси на 3-е измерение:
 [[[1]
  [2]
  [3]
  [4]
  [5]
  [6]]

 [[1]
  [2]
  [3]
  [4]
  [5]
  [6]]

 [[1]
  [2]
  [3]
  [4]
  [5]
  [6]]]


**np.squeeze** - удаление измерения (оси). Удалить можно те оси, которые имеют один элемент. Таких может быть несколько, в таком случае удаляются все, если не указаные конкретные. 

In [36]:
arr = np.array([[1,2,3,4,5,6], [1,2,3,4,5,6], [1,2,3,4,5,6]])
print(f'Исходное представление: \n{arr}')
n_arr = arr[np.newaxis, :, :, np.newaxis]
print(f'\nПредставление после добавления двух осей с одним элементом в начало и в конец: \n{n_arr}')

print(f'\nПредставление после удаления единичных осей: \n{n_arr.squeeze()}')

print(f'\nПредставление после удаления последней единичной оси: \n{n_arr.squeeze(axis = 3)}')

Исходное представление: 
[[1 2 3 4 5 6]
 [1 2 3 4 5 6]
 [1 2 3 4 5 6]]

Представление после добавления двух осей с одним элементом в начало и в конец: 
[[[[1]
   [2]
   [3]
   [4]
   [5]
   [6]]

  [[1]
   [2]
   [3]
   [4]
   [5]
   [6]]

  [[1]
   [2]
   [3]
   [4]
   [5]
   [6]]]]

Представление после удаления единичных осей: 
[[1 2 3 4 5 6]
 [1 2 3 4 5 6]
 [1 2 3 4 5 6]]

Представление после удаления последней единичной оси: 
[[[1 2 3 4 5 6]
  [1 2 3 4 5 6]
  [1 2 3 4 5 6]]]


**np.vstack** - объединение массивов по нулевой оси (по вертикали). Объединяемые массивы должны иметь одинаковый размер вдоль всех осей, кроме нулевой (по которой происходит объединение). 

In [59]:
arr1 = np.array([[1,2,3,4,5,6], [1,2,3,4,5,6], [1,2,3,4,5,6]])
arr2 = np.array([[7,8,9,10,11,12], [7,8,9,10,11,12]])

print(f'Исходное представление 1-го массива: \n{arr1}')
print(f'\nИсходное представление 2-го массива: \n{arr2}')
print(f'\nОбъединение массива по нулевой оси (по вертикали): \n{np.vstack([arr1, arr2])}')

Исходное представление 1-го массива: 
[[1 2 3 4 5 6]
 [1 2 3 4 5 6]
 [1 2 3 4 5 6]]

Исходное представление 2-го массива: 
[[ 7  8  9 10 11 12]
 [ 7  8  9 10 11 12]]

Объединение массива по нулевой оси (по вертикали): 
[[ 1  2  3  4  5  6]
 [ 1  2  3  4  5  6]
 [ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [ 7  8  9 10 11 12]]


**np.hstack** - объединение массивов по первой оси (по горизонтали). У них должен быть одинаковый размер вдоль всех осей, кроме одной (первой). Работает аналогично ***np.vstack***

In [58]:
arr1 = np.array([[1,2,3,4,5,6], [1,2,3,4,5,6], [1,2,3,4,5,6]])
arr2 = np.array([[7,8,9,10,11,12,13,14], [7,8,9,10,11,12,13,14], [7,8,9,10,11,12,13,14]])

print(f'Исходное представление 1-го массива: \n{arr1}')
print(f'\nИсходное представление 2-го массива: \n{arr2}')
print(f'\nОбъединение массива по нулевой оси (по вертикали): \n{np.hstack([arr1, arr2])}')

Исходное представление 1-го массива: 
[[1 2 3 4 5 6]
 [1 2 3 4 5 6]
 [1 2 3 4 5 6]]

Исходное представление 2-го массива: 
[[ 7  8  9 10 11 12 13 14]
 [ 7  8  9 10 11 12 13 14]
 [ 7  8  9 10 11 12 13 14]]

Объединение массива по нулевой оси (по вертикали): 
[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]]


**np.concatenate** - объединение по произвольной оси (указывается в аргументе axis). При этом для всех осей, кроме указанной, у массивов должно быть одинаковое число элементов.

In [57]:
arr1 = np.array([[1,2,3,4,5,6], [1,2,3,4,5,6], [1,2,3,4,5,6]])
arr2 = np.array([[7,8,9,10,11,12,13], [7,8,9,10,11,12,13], [7,8,9,10,11,12,13]])

print(f'Исходное представление 1-го массива: \n{arr1}')
print(f'\nИсходное представление 2-го массива: \n{arr2}')
print(f'\nОбъединение массива по нулевой оси (по вертикали): \n{np.concatenate([arr1, arr2], axis = 1)}')

Исходное представление 1-го массива: 
[[1 2 3 4 5 6]
 [1 2 3 4 5 6]
 [1 2 3 4 5 6]]

Исходное представление 2-го массива: 
[[ 7  8  9 10 11 12 13]
 [ 7  8  9 10 11 12 13]
 [ 7  8  9 10 11 12 13]]

Объединение массива по нулевой оси (по вертикали): 
[[ 1  2  3  4  5  6  7  8  9 10 11 12 13]
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13]
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13]]


**np.array_split** - разделение массивов. Первым аргументом принимает массив, вторым - на сколько элементов он должен быть разделён. Аргумент axis - ось, по которой разделяется массив. Разделённый массив - это представление исходного, поэтому последующая замена элементов меняет их и в исходном массиве. 

In [66]:
arr1 = np.array([[1,2,3,4,5,6], [1,2,3,4,5,6]])
print(f'Исходное представление массива: \n{arr1}')
print(f'\nРазделение массива на 3 части по 1-й оси: \n{np.array_split(arr1, 3, axis = 1)}')
print(f'\nРазделение массива на 2 части по 0-й оси: \n{np.array_split(arr1, 2, axis = 0)}')

Исходное представление массива: 
[[1 2 3 4 5 6]
 [1 2 3 4 5 6]]

Разделение массива на 3 части по 1-й оси: 
[array([[1, 2],
       [1, 2]]), array([[3, 4],
       [3, 4]]), array([[5, 6],
       [5, 6]])]

Разделение массива на 2 части по 0-й оси: 
[array([[1, 2, 3, 4, 5, 6]]), array([[1, 2, 3, 4, 5, 6]])]


### Добавление и удаление элементов

**np.append** - добавление данных к массиву. Первый аргумент - массив, к которому добавляются элементы. Второй аргумент - массив, элементы которого добавляются к первому. Третий аргумент - ось, по которой происходит добавление элементов. Без указания третьего аргумента функция возвращает одномерный массив из всех элементов. 

Функция создаёт копию с новыми добавленными элементами, т.е. изменение исходных массивов не повлияет на новый. Количество элементов между массивами должно отличаться только по той оси, по которой добавляются элементы. 

In [80]:
arr1 = np.array([[1,2,3,4,5,6], [1,2,3,4,5,6], [1,2,3,4,5,6]])
arr2 = np.array([[7,8,9,10,11,12,13], [7,8,9,10,11,12,13], [7,8,9,10,11,12,13]])

print(f'Исходное представление 1-го массива: \n{arr1}')
print(f'\nИсходное представление 2-го массива: \n{arr2}')
print(f'\nОбъединение массива без указания оси: \n{np.append(arr1, arr2)}')
print(f'\nОбъединение массива по 1-й оси: \n{np.append(arr1, arr2, axis = 1)}')

Исходное представление 1-го массива: 
[[1 2 3 4 5 6]
 [1 2 3 4 5 6]
 [1 2 3 4 5 6]]

Исходное представление 2-го массива: 
[[ 7  8  9 10 11 12 13]
 [ 7  8  9 10 11 12 13]
 [ 7  8  9 10 11 12 13]]

Объединение массива без указания оси: 
[ 1  2  3  4  5  6  1  2  3  4  5  6  1  2  3  4  5  6  7  8  9 10 11 12
 13  7  8  9 10 11 12 13  7  8  9 10 11 12 13]

Объединение массива по 1-й оси: 
[[ 1  2  3  4  5  6  7  8  9 10 11 12 13]
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13]
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13]]


При необходимости множественного использования функционала объединения массивов оптимальнее не циклично применять метод append, а сначала расширить массив до нужного числа элементов. И после этого, через индекс указывать элемент, которым заменить "нулевой" из расширенной части исходного массива. 
Таким образом операция будет произведена намного быстрее. 

Т.е. ***append*** лучше использовать для разового, а не цикличного добавления элементов.

**np.delete** - удаление данных из массива. Первым аргументов принимает массив, из которого производится удаление. 
Второй аргумент - индекс элемента, который нужно удалить. Третий - ось, по которой производится удаление. 

При удалении элементов с помощью функции np.delete() можно:

* передавать индекс элемента который нужно удалить: ***np.delete(..., 5, axis=...)***
* передавать список или массив с индексами элементов которые нужно удалить: ***np.delete(..., [2, 4, 19], axis=...)***
* передавать список или массив с булевыми значениями. Количество элементов в списке\массиве с булевыми значениями должно совпадать с количеством элементов оси на которой удаляются элементы. Будут удалены элементы чей индекс равен индексам значений True: ***np.delete(..., [True, False, False], axis=...)***

In [91]:
arr1 = np.array([[1,2,3,4,5,6], [1,2,3,4,5,6], [1,2,3,4,5,6]])
print(f'Исходное представление массива: \n{arr1}')
print(f'\nУдаление 1-го элемента по 0-й оси \n{np.delete(arr1, 1, axis = 0)}')
print(f'\nУдаление 1-го элемента по 1-й оси \n{np.delete(arr1, 1, axis = 1)}')

Исходное представление массива: 
[[1 2 3 4 5 6]
 [1 2 3 4 5 6]
 [1 2 3 4 5 6]]

Удаление 1-го элемента по 0-й оси 
[[1 2 3 4 5 6]
 [1 2 3 4 5 6]]

Удаление 1-го элемента по 1-й оси 
[[1 3 4 5 6]
 [1 3 4 5 6]
 [1 3 4 5 6]]


### Индексация массивов

Срезы создают новое представление массива. 
Изменение значения в таком представлении меняет и исходный массив. 

In [53]:
arr1 = np.array([[1,2,3,4,5,6], [1,2,3,4,5,6], [1,2,3,4,5,6]])
print(f'Исходное представление массива: \n{arr1}')
new_arr = arr1[0:2]
print(f'Представление с первыми двумя осями: \n{new_arr}')
new_arr[0,3] = 10
print(f'Представление исходного массива после присвоения элементу (0,3) нового массива значения 10: \n{arr1}')

Исходное представление массива: 
[[1 2 3 4 5 6]
 [1 2 3 4 5 6]
 [1 2 3 4 5 6]]
Представление с первыми двумя осями: 
[[1 2 3 4 5 6]
 [1 2 3 4 5 6]]
Представление исходного массива после присвоения элементу (0,3) нового массива значения 10: 
[[ 1  2  3 10  5  6]
 [ 1  2  3  4  5  6]
 [ 1  2  3  4  5  6]]


При списочной индексации создаётся копия массива и его изменение не затронет исходный массив. 

In [55]:
arr1 = np.array([[1,2,3,4,5,6], [1,2,3,4,5,6], [1,2,3,4,5,6]])
print(f'Исходное представление массива: \n{arr1}')
new_arr = arr1[[0,1]]
print(f'Представление с первыми двумя осями: \n{new_arr}')
new_arr[0,3] = 10
print(f'Представление исходного массива после присвоения элементу (0,3) нового массива значения 10: \n{arr1}')
print(f'Представление нового массива после присвоения элементу (0,3) нового массива значения 10: \n{new_arr}')

Исходное представление массива: 
[[1 2 3 4 5 6]
 [1 2 3 4 5 6]
 [1 2 3 4 5 6]]
Представление с первыми двумя осями: 
[[1 2 3 4 5 6]
 [1 2 3 4 5 6]]
Представление исходного массива после присвоения элементу (0,3) нового массива значения 10: 
[[1 2 3 4 5 6]
 [1 2 3 4 5 6]
 [1 2 3 4 5 6]]
Представление нового массива после присвоения элементу (0,3) нового массива значения 10: 
[[ 1  2  3 10  5  6]
 [ 1  2  3  4  5  6]]


Также при списочной индексации, если индексируется несколько осей, то можно выбрать конкретные элементы на каждой оси

In [66]:
arr1 = np.array([[1,2,3,4,5,6], [1,2,3,4,5,6], [1,2,3,4,5,6]])
print(f'Исходное представление массива: \n{arr1}')
print(f'\nСрез с элементами (2,3,5) для осей (0,1,2) соответственно:')
print(arr1[[0,1,2],[2,3,5]])
print(f'\nСрез с элементами (2,3,5) для нулевой оси, (4,3,1) для первой оси и (1,5,1) для третьей оси:')
print(arr1[[0,1,2],[[2,3,5],[4,3,1],[1,5,1]]])

Исходное представление массива: 
[[1 2 3 4 5 6]
 [1 2 3 4 5 6]
 [1 2 3 4 5 6]]

Срез с элементами (2,3,5) для осей (0,1,2) соответственно:
[3 4 6]

Срез с элементами (2,3,5) для нулевой оси, (4,3,1) для первой оси и (1,5,1) для третьей оси:
[[3 4 6]
 [5 4 2]
 [2 6 2]]


### Математические операции между массивами

Математические операции между массивами и числами, а также между массивами одного размера могут проводиться без ограничений.

In [74]:
arr1 = np.array([[1,2,3,4,5,6], [1,2,3,4,5,6], [1,2,3,4,5,6]])
print(f'Исходное представление массива: \n{arr1}')
print(f'Представление исходного массива, прибавленное к 2: \n{arr1+2}')
print(f'Представление исходного массива, умноженное на 2: \n{arr1*2}')
print(f'Представление исходного массива в степени 2: \n{arr1**2}')

arr2 = np.array([[10,20,30,40,50,60], [100,200,300,400,500,600], [0.1,0.2,0.3,0.4,0.5,0.6]])
print(f'Исходное представление второго массива: \n{arr2}')
print(f'Представление умножения массивов: \n{arr1*arr2}')

Исходное представление массива: 
[[1 2 3 4 5 6]
 [1 2 3 4 5 6]
 [1 2 3 4 5 6]]
Представление исходного массива, прибавленное к 2: 
[[3 4 5 6 7 8]
 [3 4 5 6 7 8]
 [3 4 5 6 7 8]]
Представление исходного массива, умноженное на 2: 
[[ 2  4  6  8 10 12]
 [ 2  4  6  8 10 12]
 [ 2  4  6  8 10 12]]
Представление исходного массива в степени 2: 
[[ 1  4  9 16 25 36]
 [ 1  4  9 16 25 36]
 [ 1  4  9 16 25 36]]
Исходное представление второго массива: 
[[1.e+01 2.e+01 3.e+01 4.e+01 5.e+01 6.e+01]
 [1.e+02 2.e+02 3.e+02 4.e+02 5.e+02 6.e+02]
 [1.e-01 2.e-01 3.e-01 4.e-01 5.e-01 6.e-01]]
Представление умножения массивов: 
[[1.0e+01 4.0e+01 9.0e+01 1.6e+02 2.5e+02 3.6e+02]
 [1.0e+02 4.0e+02 9.0e+02 1.6e+03 2.5e+03 3.6e+03]
 [1.0e-01 4.0e-01 9.0e-01 1.6e+00 2.5e+00 3.6e+00]]


Операции между массивами разного размера могут проводиться с помощью процедуры транслирования.

Если массивы имеют разное количество осей, то: 
* К массиву с меньшим количеством добавляются новые, чтобы размерности совпали. Автоматически добавление происходит слева.
* В массивах на соответствующих осяй должно быть одинаковое количество элементов, либо один элемент в одном из массивов (на одной из осей).

In [129]:
arr1 = np.ones([3,6])
arr2 = np.eye(4,5)
print(f'Исходное представление 1-го массива: \n{arr1}')
print(f'\nИсходное представление 2-го массива: \n{arr2}')

Исходное представление 1-го массива: 
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]

Исходное представление 2-го массива: 
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]


Нельзя умножить массивы разной размерности напрямую: (3,6) и (4,5)

Но можно изменить размерность одного из массивов, чтобы их можно было умножить.

Наилучшее изменение зависит от конкретной задачи. 

In [128]:
print(f'\nДопустимые произведения: \n - (3,6,1,1) и (4,5): \n\n{(arr1.reshape(3,6,1,1) * arr2)[:2, :2]}')
print(f'\n- (3,6) и (4,5,1,1): \n\n{(arr1*arr2.reshape(4,5,1,1))[:2, :2]}')
print(f'\n- (1,3,6,1) и (4,1,1,5): \n\n{(arr1.reshape(1,3,6,1)*arr2.reshape(4,1,1,5))[:2, :2]}')


Допустимые произведения: 
 - (3,6,1,1) и (4,5): 

[[[[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]]]


 [[[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]]]]

- (3,6) и (4,5,1,1): 

[[[[1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]]

  [[0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0.]]]


 [[[0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0.]]

  [[1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1.]]]]

- (1,3,6,1) и (4,1,1,5): 

[[[[1. 0. 0. 0. 0.]
   [1. 0. 0. 0. 0.]
   [1. 0. 0. 0. 0.]
   [1. 0. 0. 0. 0.]
   [1. 0. 0. 0. 0.]
   [1. 0. 0. 0. 0.]]

  [[1. 0. 0. 0. 0.]
   [1. 0. 0. 0. 0.]
   [1. 0. 0. 0. 0.]
   [1. 0. 0. 0. 0.]
   [1. 0. 0. 0. 0.]
   [1. 0. 0. 0. 0.]]]


 [[[0. 1. 0. 0. 0.]
   [0. 1. 0. 

### Вычислительные функции

**np.abs** - модуль числа. Если необходимо вернуть число типа ***float***, то используется функция **np.fabs**.

**np.min, np.max** - минимальное и максимальное значения.

**np.sqrt, np.square** - квадратный корень, и квадратная степень числа. 

**np.argmin, np.argmax** - индексы элементов, которые являются минимальными и максимальными значениями. 

**np.sum, np.mean, np.std** - сумма, средняя, стандартное отклонение элементов. 

**np.exp, np.log** - экспонента и натуральный логарифм элемента. 

**np.log2, np.log1p** - логарифм по основанию 2, и натуральный логарифм числа 1+x, соответственно.

**np.sign** - определение знака числа. Возвращает -1, если знак отрицательный, 0 для нуля и 1 если положительный.

**np.modf** - определение целой и дробной части числа. Возвращает два массива - массив целых чисел и массив дробных чисел.

Функции можно применять как самостоятельные, либо как методы массива. Запись ***np.array.mean()*** эквивалентна записи ***np.mean(array)***.

In [163]:
arr1 = np.array([[1,2,3,4,5,6], [1,2,3,4,5,6], [1,2,3,4,5,6]])
print(f'Исходное представление массива: \n{arr1}')
print(f'\nСреднее значение как метод массива arr1.mean(): {arr1.mean()}')
print(f'Среднее значение функция с аргументом в виде массива: np.mean(arr1): {np.mean(arr1)}')

Исходное представление массива: 
[[1 2 3 4 5 6]
 [1 2 3 4 5 6]
 [1 2 3 4 5 6]]

Среднее значение как метод массива arr1.mean(): 3.5
Среднее значение функция с аргументом в виде массива: np.mean(arr1): 3.5


В многомерном массиве функции агрегации могут применять относительной отдельных осей. 

In [171]:
arr1 = np.array([np.array([1,2,3,4,5,6]), np.array([1,2,3,4,5,6])*2, np.array([1,2,3,4,5,6])*3])

print(f'Исходное представление массива: \n{arr1}')
print(f'\nСуммы относительно 0-й оси: \n{arr1.sum(axis = 0)}')
print(f'\nСуммы относительно 1-й оси: \n{arr1.sum(axis = 1)}')

Исходное представление массива: 
[[ 1  2  3  4  5  6]
 [ 2  4  6  8 10 12]
 [ 3  6  9 12 15 18]]

Суммы относительно 0-й оси: 
[ 6 12 18 24 30 36]

Суммы относительно 1-й оси: 
[21 42 63]


In [179]:
arr1 = np.empty([3,4,2], dtype = np.int32)

print(f'Исходное представление массива: \n{arr1}')
print(f'\nСуммы относительно 0-й оси: \n{arr1.sum(axis = 0)}')
print(f'\nСуммы относительно 1-й оси: \n{arr1.sum(axis = 1)}')
print(f'\nСуммы относительно 0-й и 1-й оси: \n{arr1.sum(axis = (0,1))}')
print(f'\nСуммы относительно 1-й и 2-й оси: \n{arr1.sum(axis = (1,2))}')

Исходное представление массива: 
[[[         0 1072693248]
  [         0 1072693248]
  [         0 1072693248]
  [         0 1072693248]]

 [[         0 1072693248]
  [         0 1072693248]
  [         0 1072693248]
  [         0 1072693248]]

 [[         0 1072693248]
  [         0 1072693248]
  [         0 1072693248]
  [         0 1072693248]]]

Суммы относительно 0-й оси: 
[[          0 -1076887552]
 [          0 -1076887552]
 [          0 -1076887552]
 [          0 -1076887552]]

Суммы относительно 1-й оси: 
[[       0 -4194304]
 [       0 -4194304]
 [       0 -4194304]]

Суммы относительно 0-й и 1-й оси: 
[        0 -12582912]

Суммы относительно 1-й и 2-й оси: 
[-4194304 -4194304 -4194304]


**np.cumsum, np.cumprod** - кумулятивная сумма и кумулятивное произведение элементов. По умолчанию операция выполняется над одномерным массивом или после приведения к нему. В аргументе axis может быть указано, относительно какой оси выполнять операцию.

**np.ptp** - разница между максимальным и минимальным значениями в массиве. По умолчанию операция выполняется над одномерным массивом или после приведения к нему. В аргументе axis может быть указано, относительно какой оси выполнять операцию.

**np.diff** - разница между соседними элементами массива. По умолчанию операция выполняется по последней оси (axis = -1). 

In [28]:
arr1 = np.array([np.array([1,2,3,4,5,6]), np.array([1,2,3,4,5,6])*2, np.array([1,2,3,4,5,6])*3])

print(f'Исходное представление массива: \n{arr1}')
print(f'\nКумулятивная сумма по плоскому массиву: \n{np.cumsum(arr1)}')
print(f'\nКумулятивная сумма по нулевой оси: \n{np.cumsum(arr1, axis = 0)}')
print(f'\nКумулятивная сумма по первой оси: \n{np.cumsum(arr1, axis = 1)}')

Исходное представление массива: 
[[ 1  2  3  4  5  6]
 [ 2  4  6  8 10 12]
 [ 3  6  9 12 15 18]]

Кумулятивная сумма по плоскому массиву: 
[  1   3   6  10  15  21  23  27  33  41  51  63  66  72  81  93 108 126]

Кумулятивная сумма по нулевой оси: 
[[ 1  2  3  4  5  6]
 [ 3  6  9 12 15 18]
 [ 6 12 18 24 30 36]]

Кумулятивная сумма по первой оси: 
[[ 1  3  6 10 15 21]
 [ 2  6 12 20 30 42]
 [ 3  9 18 30 45 63]]


In [30]:
arr1 = np.array([np.array([1,2,3,4,5,6]), np.array([1,2,3,4,5,6])*2, np.array([1,2,3,4,5,6])*3])

print(f'Исходное представление массива: \n{arr1}')
print(f'\nРазница мин-макс по плоскому массиву: \n{np.ptp(arr1)}')
print(f'\nРазница мин-макс по нулевой оси: \n{np.ptp(arr1, axis = 0)}')
print(f'\nРазница мин-макс по первой оси: \n{np.ptp(arr1, axis = 1)}')

Исходное представление массива: 
[[ 1  2  3  4  5  6]
 [ 2  4  6  8 10 12]
 [ 3  6  9 12 15 18]]

Разница мин-макс по плоскому массиву: 
17

Разница мин-макс по нулевой оси: 
[ 2  4  6  8 10 12]

Разница мин-макс по первой оси: 
[ 5 10 15]


In [31]:
arr1 = np.array([np.array([1,2,3,4,5,6]), np.array([1,2,3,4,5,6])*2, np.array([1,2,3,4,5,6])*3])

print(f'Исходное представление массива: \n{arr1}')
print(f'\nРазница мин-макс по плоскому массиву: \n{np.diff(arr1)}')
print(f'\nРазница мин-макс по нулевой оси: \n{np.diff(arr1, axis = 0)}')
print(f'\nРазница мин-макс по первой оси: \n{np.diff(arr1, axis = 1)}')

Исходное представление массива: 
[[ 1  2  3  4  5  6]
 [ 2  4  6  8 10 12]
 [ 3  6  9 12 15 18]]

Разница мин-макс по плоскому массиву: 
[[1 1 1 1 1]
 [2 2 2 2 2]
 [3 3 3 3 3]]

Разница мин-макс по нулевой оси: 
[[1 2 3 4 5 6]
 [1 2 3 4 5 6]]

Разница мин-макс по первой оси: 
[[1 1 1 1 1]
 [2 2 2 2 2]
 [3 3 3 3 3]]


**np.bincount** - расчёт частоты встречаемости каждого неотрицательного целого числа в массиве. Массив может содержать только неотрицательные целые числа. Применяется к одномерному массиву, либо должен быть предварительно приведён к нему. Выводит массив, содержащий число повторений целых значений между минимальным и максимальным в исходном массиве.

In [54]:
arr1 = np.array([np.array([1,2,3,4,5,6]), np.array([1,2,3,4,5,6])*2, np.array([1,2,3,4,5,6])*3])

print(f'Исходное представление массива: \n{arr1}')
print(f'\nПредставление приведённого одномерного массива: \n{arr1.reshape(18)}')
print(f'\nСортированный массив: \n{np.sort(arr1.reshape(18))}')
print(f'\nРезультат применения np.bincount: \n{np.bincount(arr1.reshape(18))}')

Исходное представление массива: 
[[ 1  2  3  4  5  6]
 [ 2  4  6  8 10 12]
 [ 3  6  9 12 15 18]]

Представление приведённого одномерного массива: 
[ 1  2  3  4  5  6  2  4  6  8 10 12  3  6  9 12 15 18]

Сортированный массив: 
[ 1  2  2  3  3  4  4  5  6  6  6  8  9 10 12 12 15 18]

Результат применения np.bincount: 
[0 1 2 2 2 1 3 0 1 1 1 0 2 0 0 1 0 0 1]


**np.sort** - сортировка массива. Первым аргументом принимает массив, который нужно отсортировать, вторым - ось, по которой производится сортировка. 

In [9]:
arr1 = np.array([np.array([1,2,3,4,5,6]), np.array([1,2,3,4,5,6])*3, np.array([1,2,3,4,5,6])*2])
print(f'Исходное представление массива: \n{arr1}')
print(f'\nСортированный массив (по умолчанию сортировка по последней оси): \n{np.sort(arr1)}')
print(f'\nСортировка по нулевой оси: \n{np.sort(arr1, axis = 0)}')
print(f'\nСортировка плоского массива: \n{np.sort(arr1, axis = None)}')

Исходное представление массива: 
[[ 1  2  3  4  5  6]
 [ 3  6  9 12 15 18]
 [ 2  4  6  8 10 12]]

Сортированный массив (по умолчанию сортировка по последней оси): 
[[ 1  2  3  4  5  6]
 [ 3  6  9 12 15 18]
 [ 2  4  6  8 10 12]]

Сортировка по нулевой оси: 
[[ 1  2  3  4  5  6]
 [ 2  4  6  8 10 12]
 [ 3  6  9 12 15 18]]

Сортировка плоского массива: 
[ 1  2  2  3  3  4  4  5  6  6  6  8  9 10 12 12 15 18]


**np.unique** - определение уникальных элементов массива. Опциональные параметры: 
* return_index: Если True, то также возвращает массив индексов первого вхождения уникальных элементов.
* return_inverse: Если True, то также возвращает массив, который при использовании как индекс восстанавливает исходный массив.
* return_counts: Если True, то также возвращает массив, содержащий количество вхождений каждого уникального элемента.
* axis: Опциональный параметр, указывающий ось, по которой нужно найти уникальные элементы. Если не указан, поиск производится по всему массиву.

In [19]:
arr1 = np.array([np.array([1,2,3,4,5,6]), np.array([1,2,3,4,5,6])*3, np.array([1,2,3,4,5,6])*2])
print(f'Исходное представление массива: \n{arr1}')
print(f'\nУникальные элементы массива: \n{np.unique(arr1)}')

print(f'\nУникальные элементы массива с индексами их первого вхождения: \n{np.unique(arr1, return_index = True)}')
print(f'\nУникальные элементы массива с индексами всех вхождений: \n{np.unique(arr1, return_inverse = True)}')
print(f'\nУникальные элементы массива с количеством вхождений каждого элемента: \n{np.unique(arr1, return_counts = True)}')

Исходное представление массива: 
[[ 1  2  3  4  5  6]
 [ 3  6  9 12 15 18]
 [ 2  4  6  8 10 12]]

Уникальные элементы массива: 
[ 1  2  3  4  5  6  8  9 10 12 15 18]

Уникальные элементы массива с индексами их первого вхождения: 
(array([ 1,  2,  3,  4,  5,  6,  8,  9, 10, 12, 15, 18]), array([ 0,  1,  2,  3,  4,  5, 15,  8, 16,  9, 10, 11], dtype=int64))

Уникальные элементы массива с индексами всех вхождений: 
(array([ 1,  2,  3,  4,  5,  6,  8,  9, 10, 12, 15, 18]), array([ 0,  1,  2,  3,  4,  5,  2,  5,  7,  9, 10, 11,  1,  3,  5,  6,  8,
        9], dtype=int64))

Уникальные элементы массива с количеством вхождений каждого элемента: 
(array([ 1,  2,  3,  4,  5,  6,  8,  9, 10, 12, 15, 18]), array([1, 2, 2, 2, 1, 3, 1, 1, 1, 2, 1, 1], dtype=int64))


### Функции округления

**np.ceil** - вычисляет наименьшее целое число, не меньшее каждого элемента массива (округление по верхней границе).

**np.floor** - вычисляет наибольшее целое число, не большее каждого элемента массива (округление по нижней границе).

**np.rint** - округляет элементы массива до ближайшего целого числа, используя правило "банковского" округления. В банковском округлении дробная часть, равная 0.5 в чётных числах округляется в меньшую сторону, в нечётных - в большую.

**np.round** - округление с указанием разрядности. Если разрядность равна нулю, результат совпадает с результатом функции **np.rint**.

**np.trunc** - округление до ближайшего целого числа. 

In [32]:
arr1 = np.array([2.3, 2.5, 3.7, 1.6, 4.9, 3.5])
print(f'Исходный массив: \n{arr1}')
print(f'\nОкругление по верхней границе: \n{np.ceil(arr1)}')
print(f'\nОкругление по нижней границе: \n{np.floor(arr1)}')
print(f'\nОкругление до ближайшего целого методом np.rint: \n{np.rint(arr1)}')
print(f'\nОкругление с указанием разрядности (равна нулю): \n{np.round(arr1, 0)}')
print(f'\nОкругление до ближайшего целого методом np.trunc: \n{np.trunc(arr1)}')

Исходный массив: 
[2.3 2.5 3.7 1.6 4.9 3.5]

Округление по верхней границе: 
[3. 3. 4. 2. 5. 4.]

Округление по нижней границе: 
[2. 2. 3. 1. 4. 3.]

Округление до ближайшего целого методом np.rint: 
[2. 2. 4. 2. 5. 4.]

Округление с указанием разрядности (равна нулю): 
[2. 2. 4. 2. 5. 4.]

Округление до ближайшего целого методом np.trunc: 
[2. 2. 3. 1. 4. 3.]


### Проверка условий

**np.isin** - проверка на вхождение значениий одного массива в другом. Первым аргументом принимает значения массива, наличие которых проверяется (IS). Вторым аргументом - массив, в котором ищутся эти значения (IN). 

**np.isnan** - проверка на отсутствие значения в массиве. 

**np.isfinite** - проверка на конечность значений в массиве. 

**np.isinf** - проверка на бесконечность значений в массиве. 

In [39]:
arr1 = np.array([2.3, 2.5, np.nan, 1.6, np.inf, 3.5])
arr2 = np.array([1, 3.5])

print(f'Исходный массив: \n{arr1}')
print(f'\nПроверка значений: \n{arr2}')

print(f'\nПроверка на вхождение значений: \n{np.isin(arr1, arr2)}')

print(f'\nПроверка на отсутствующие значения: \n{np.isnan(arr1)}')

print(f'\nПроверка на конечность значений: \n{np.isfinite(arr1)}')

print(f'\nПроверка на бесконечность значений: \n{np.isinf(arr1)}')

Исходный массив: 
[2.3 2.5 nan 1.6 inf 3.5]

Проверка значений: 
[1.  3.5]

Проверка на вхождение значений: 
[False False False False False  True]

Проверка на отсутствующие значения: 
[False False  True False False False]

Проверка на конечность значений: 
[ True  True False  True False  True]

Проверка на бесконечность значений: 
[False False False False  True False]


### Вычислительные функции между массивами (бинарные операции)

**np.add** - поэлементное сложение массивов. 

**np.subtract** - вычитание поэлементно значений массива, переданного вторым аргументом, из значений массива, переданного первым.

**np.multiply** - поэлементное произведение массивов.

**np.divide** - поэлементное деление элементов, переданных в массиве в первом аргументе, на элементы массива, переданного вторым аргументом. 

**np.floor_divide** - аналог функции **np.divide**, но с округлением до наименьшего целого.

**np.power** - возведение элементов из первого массива в степени, указанные во втором массиве.

In [24]:
arr1 = np.array([2.3, 2.5, 3.7, 1.6, 4.9, 3.5])
arr2 = np.array([2, 3, 1.5, 2, 5, 3])

print(f'Исходный массив 1: {arr1}')
print(f'Исходный массив 2: {arr2}')

print(f'\nСложение массивов через np.add: {np.add(arr1, arr2)}')
print(f'\nВычитание массивов через np.subtract: {np.subtract(arr1, arr2)}')
print(f'\nУмножение массивов через np.multiply: {np.multiply(arr1, arr2)}')
print(f'\nДеление массивов через np.divide: {np.divide(arr1, arr2)}')
print(f'\nДеление массивов через np.floor_divide: {np.floor_divide(arr1, arr2)}')
print(f'\nВозведение массивов в степень: \n{np.power(arr1, arr2)}')

Исходный массив 1: [2.3 2.5 3.7 1.6 4.9 3.5]
Исходный массив 2: [2.  3.  1.5 2.  5.  3. ]

Сложение массивов через np.add: [4.3 5.5 5.2 3.6 9.9 6.5]

Вычитание массивов через np.subtract: [ 0.3 -0.5  2.2 -0.4 -0.1  0.5]

Умножение массивов через np.multiply: [ 4.6   7.5   5.55  3.2  24.5  10.5 ]

Деление массивов через np.divide: [1.15       0.83333333 2.46666667 0.8        0.98       1.16666667]

Деление массивов через np.floor_divide: [1. 0. 2. 0. 0. 1.]

Возведение массивов в степень: 
[5.29000000e+00 1.56250000e+01 7.11709210e+00 2.56000000e+00
 2.82475249e+03 4.28750000e+01]


**np.maximum** - возвращает поэлементный максимум двух массивов. 

**np.fmax** - аналогично **np.maximum**, но игнорируя отсутствующие значения NaN.

**np.minimum** - возвращает поэлементный минимум двух массивов. 

**np.fmin** - аналогично **np.minimum**, но игнорируя отсутствующие значения NaN.

In [29]:
arr1 = np.array([2.3, 2.5, 3.7, 1.6, np.nan, 3.5])
arr2 = np.array([2, 3, np.nan, 2, 5, 3])

print(f'Исходный массив 1: {arr1}')
print(f'Исходный массив 2: {arr2}')

print(f'\nОпределение максимума через np.maximum: {np.maximum(arr1, arr2)}')
print(f'\nОпределение максимума через np.fmax: {np.fmax(arr1, arr2)}')

print(f'\nОпределение минимума через np.minimum: {np.maximum(arr1, arr2)}')
print(f'\nОпределение минимума через np.fmin: {np.fmax(arr1, arr2)}')

Исходный массив 1: [2.3 2.5 3.7 1.6 nan 3.5]
Исходный массив 2: [ 2.  3. nan  2.  5.  3.]

Определение максимума через np.maximum: [2.3 3.  nan 2.  nan 3.5]

Определение максимума через np.fmax: [2.3 3.  3.7 2.  5.  3.5]

Определение минимума через np.minimum: [2.3 3.  nan 2.  nan 3.5]

Определение минимума через np.fmin: [2.3 3.  3.7 2.  5.  3.5]


**np.mod** - вычисляет остаток от деления элементов первого массива на соответствующие элементы второго массива (либо заданнаго числа). 

In [30]:
arr1 = np.array([2.3, 2.5, 3.7, 1.6, 4.9, 3.5])
arr2 = np.array([2, 3, 1.5, 2, 5, 3])

print(f'Исходный массив 1: {arr1}')
print(f'Исходный массив 2: {arr2}')

print(f'\nОстаток от деления первого массива на второй: {np.mod(arr1, arr2)}')
print(f'\nОстаток от деления первого массива на 3: {np.mod(arr1, 3)}')

Исходный массив 1: [2.3 2.5 3.7 1.6 4.9 3.5]
Исходный массив 2: [2.  3.  1.5 2.  5.  3. ]

Остаток от деления первого массива на второй: [0.3 2.5 0.7 1.6 4.9 0.5]

Остаток от деления первого массива на 3: [2.3 2.5 0.7 1.6 1.9 0.5]


**np.copysign** - копирует знак значения из второго массива в значения первого массива.

In [31]:
arr1 = np.array([2.3, 2.5, 3.7, 1.6, 4.9, 3.5])
arr2 = np.array([2, -3, -1.5, 2, 5, -3])

print(f'Исходный массив 1: {arr1}')
print(f'Исходный массив 2: {arr2}')

print(f'\nКопирование знака второго массива в 1-й: {np.copysign(arr1, arr2)}')

Исходный массив 1: [2.3 2.5 3.7 1.6 4.9 3.5]
Исходный массив 2: [ 2.  -3.  -1.5  2.   5.  -3. ]

Копирование знака второго массива в 1-й: [ 2.3 -2.5 -3.7  1.6  4.9 -3.5]


### Генерация случайных чисел

**np.random.rand()** - создаёт число или массив из равномерного распределения от 0 до 1. Если передавать в функцию несколько чисел, то это будет массив соответствующей размерности.

In [13]:
print(f'Функция без аргументов возращает одно число: {np.random.rand()}')
print(f'\nФункция с одним аргументом возвращает одномерный массив соответствующего размера: \n{np.random.rand(5)}')

print(f'\nФункция с несколькими аргументами возвращает массив соответствующей размерности: \n{np.random.rand(5,3)}')

Функция без аргументов возращает одно число: 0.5065376904556314

Функция с одним аргументом возвращает одномерный массив соответствующего размера: 
[0.9359608  0.68075262 0.8961514  0.0478863  0.63579677]

Функция с несколькими аргументами возвращает массив соответствующей размерности: 
[[0.78978876 0.73143118 0.89196062]
 [0.10530297 0.78065903 0.03526031]
 [0.31614984 0.00101542 0.23177978]
 [0.22225891 0.86960196 0.97408733]
 [0.40294204 0.47107096 0.26630465]]


**np.random.randn()** - создаёт число или массив из стандартного нормального распределения. 

In [14]:
print(f'Функция без аргументов возращает одно число: {np.random.randn()}')
print(f'\nФункция с одним аргументом возвращает одномерный массив соответствующего размера: \n{np.random.randn(5)}')

print(f'\nФункция с несколькими аргументами возвращает массив соответствующей размерности: \n{np.random.randn(5,3)}')

Функция без аргументов возращает одно число: 0.9861779138652399

Функция с одним аргументом возвращает одномерный массив соответствующего размера: 
[ 1.36415429 -0.7498241   0.12447417 -0.11397631  0.47836857]

Функция с несколькими аргументами возвращает массив соответствующей размерности: 
[[-1.6173615   0.85325236 -0.36372279]
 [-0.06410108  0.01150829  0.61464558]
 [ 0.98104057  0.1645479   0.18062994]
 [ 0.83738092  2.55367494  0.23160664]
 [ 2.78992351  1.89568065  1.17281768]]


**np.random.normal()** - создаёт число или массив из нормального распределения с заданным средним и стандартным отклонением. Первые два аргумента - среднее и стандартное отклонение. Третий аргумент - число или список, отвечающий за размерность массива. 

*Функция без аргументов* возращает одно число из стандартного нормального распределения:

In [28]:
np.random.normal()

-1.1110181198631675

_Функция с одним аргументом_ возвращает одно число из нормального распределения со средним, равным указанному числу и стандартным отклонением 1:

In [29]:
np.random.normal(5)

5.4429413414471615

*Функция с двумя аргументами* возвращает одно число из нормального распределения с указанным средним и стандартным отклонением:

In [30]:
np.random.normal(5,3)

2.9242052808740255

*Функция с тремя аргументами* возвращает массив из нормального распределения с указанным средним и стандартным отклонением, где третье число - размерность массива.

In [31]:
np.random.normal(5,3, 10)

array([ 4.7632117 ,  6.90654486,  9.52804867,  5.80812063, 10.02797134,
        3.11509931,  3.85131623,  3.85269392,  1.24024069,  5.28146386])

In [36]:
np.random.normal(5,3, [5,5])

array([[8.28030603, 1.3171138 , 8.21491967, 0.98165249, 4.0669157 ],
       [3.20800053, 8.06215585, 8.49614106, 0.6196539 , 0.18188826],
       [7.5170297 , 4.52098022, 2.61248394, 0.84318576, 9.91701045],
       [0.72997504, 3.64108515, 4.59055941, 4.24707943, 7.64811376],
       [5.1760886 , 9.38316921, 2.50568159, 4.99313287, 7.9697383 ]])

**np.random.randint()** - число или массив из дискретного равномерного распределения. По умолчанию распределение начинается от нуля. Первый аргумент - последнее значение не включительно. Второй аргумент - начало распределения. Третий аргумент (size) отвечает за размерность, принимает число, список или кортеж.

In [39]:
np.random.randint(10)

4

In [40]:
np.random.randint(5,10)

8

In [41]:
np.random.randint(5,10,10)

array([6, 6, 7, 7, 6, 5, 9, 6, 7, 7])

In [42]:
np.random.randint(5,10,[5,5])

array([[9, 5, 5, 5, 5],
       [7, 8, 9, 6, 8],
       [6, 9, 6, 7, 9],
       [7, 8, 9, 5, 6],
       [9, 6, 9, 6, 6]])

**np.random.multivariate_normal** - генерация выборок из многомерного нормального распределения, где N - мерность пространства случайных величин. Необходимо указать:
* m - вектор математических ожиданий (размерности N);
* cov - матрицу ковариаций (размерности NxN);
* N - объём выборки.

Двумерная нормально распределённая случайная величина со средними значениями (5, 5) и корреляцией, равной 0,5.

In [111]:
np.random.multivariate_normal([5,5], [[1,0.5], [0.5,1]], 10)

array([[4.19661981, 3.81543714],
       [4.5183844 , 4.79787163],
       [5.57584871, 5.26547092],
       [3.19510536, 5.16564858],
       [3.2978313 , 3.5206983 ],
       [6.26265309, 6.26371523],
       [4.68281611, 6.12956153],
       [5.25039127, 5.50900017],
       [6.61201311, 5.31855565],
       [5.5491933 , 5.85467909]])

In [107]:
arr = np.random.multivariate_normal([5,5], [[1,0.5], [0.5,1]], 10)
np.corrcoef(arr[:,0], arr[:,1])[0,1]

0.8491437764148063

Если в объёме выборки вместо числа будет указан кортеж, то его первое число будет означать номер наблюдения, второе - число дополнительных случайных величин с теми же параметрами.

**np.random.choice()** - получение указанного количества элементов из массива, выбранных случайным образом. Первый аргумент - массив, откуда элементы выбираются. Второй - число значений. 

In [43]:
np.random.choice(np.random.normal(5,3,10), 3)

array([3.99198900e+00, 3.77040023e+00, 3.43751496e-03])

In [44]:
np.random.choice(np.array([1,2,3,4,5,6]), 3)

array([1, 5, 3])

**np.random.shuffle()** - перемешивание массива вдоль нулевой оси. Функция меняет порядок элементов в массиве. 

**np.random.permutation()** - работает аналогично ***shuffle***, но возвращает новый массив, не меняя исходный.

In [69]:
arr1 = np.array([np.array([1,2,3,4,5,6]), np.array([1,2,3,4,5,6])*2, np.array([1,2,3,4,5,6])*3])
print(f'Исходное представление массива: \n{arr1}')
np.random.shuffle(arr1)
print(f'\nПредставление массива после перемешивания shuffle: \n{arr1}')
print(f'\nПрименение перемешивания permutation: \n{np.random.permutation(arr1)}')
print(f'\nПредставление массива после перемешивания permutation: \n{arr1}')

Исходное представление массива: 
[[ 1  2  3  4  5  6]
 [ 2  4  6  8 10 12]
 [ 3  6  9 12 15 18]]

Представление массива после перемешивания shuffle: 
[[ 1  2  3  4  5  6]
 [ 3  6  9 12 15 18]
 [ 2  4  6  8 10 12]]

Применение перемешивания permutation: 
[[ 2  4  6  8 10 12]
 [ 1  2  3  4  5  6]
 [ 3  6  9 12 15 18]]

Представление массива после перемешивания permutation: 
[[ 1  2  3  4  5  6]
 [ 3  6  9 12 15 18]
 [ 2  4  6  8 10 12]]


**np.random.seed()** - выбор одного сценария генерации случайных значений, для обеспечения воспроизводимости. В аргументе может быть указано любое число. После этой функции могут выполняться другие команды, связанные со случайными значениями и они не будут меняться. 

In [55]:
np.random.seed(40)
np.random.rand(3)

array([0.40768703, 0.05536604, 0.78853488])

### Операции сравнения

Операции сравнения в массивах проводятся поэлементно. Для задания условия сравнения можно использовать оператор сравнения или соответствующую функцию ***numpy***:
* ">" = np.greater
* ">=" = np.greater_equal
* "<" = np.less
* "<=" = np.less_equal
* "==" = np.equal
* "!=" = np.not_equal

In [93]:
arr1 = np.array([np.array([1,2,3,4,5,6]), np.array([1,2,3,4,5,6])*2, np.array([1,2,3,4,5,6])*3])
print(f'Исходное представление массива: \n{arr1}')
print(f'Сравнение по условию >= 5: \n{arr1 >= 5}')
print(f'Сравнение по условию <= 10: \n{np.less_equal(arr1, 10)}')

Исходное представление массива: 
[[ 1  2  3  4  5  6]
 [ 2  4  6  8 10 12]
 [ 3  6  9 12 15 18]]
Сравнение по условию >= 5: 
[[False False False False  True  True]
 [False False  True  True  True  True]
 [False  True  True  True  True  True]]
Сравнение по условию <= 10: 
[[ True  True  True  True  True  True]
 [ True  True  True  True  True False]
 [ True  True  True False False False]]


Условие можно использовать в качестве среза массива, указав его в квадратных скобках к массиву. Многомерный массив при этом преобразуется в одномерный.

In [99]:
arr1 = np.array([np.array([1,2,3,4,5,6]), np.array([1,2,3,4,5,6])*2, np.array([1,2,3,4,5,6])*3])
print(f'Исходное представление массива: \n{arr1}')
print(f'Фильтрация массива по условию "> 5": \n{arr1[arr1 > 5]}')

Исходное представление массива: 
[[ 1  2  3  4  5  6]
 [ 2  4  6  8 10 12]
 [ 3  6  9 12 15 18]]
Фильтрация массива по условию "> 5": 
[ 6  6  8 10 12  6  9 12 15 18]


**np.any** - принимает массив с булевыми значениями. Возвращает *True* если хотя бы одно из них *True*.

**np.all** - принимает массив с булевыми значениями. Возвращает *False* если хотя бы один из них *False*.

Обе функции могут применяться только по одной выбранной оси, или нескольким выбранным (задаются с помощью кортежа). 

In [102]:
arr = [True, True, False, True]
print(f'Исходное представление массива: \n{arr}')
print(f'\nПрименение к массиву функции np.any: {np.any(arr)}')
print(f'\nПрименение к массиву функции np.all: {np.all(arr)}')

Исходное представление массива: 
[True, True, False, True]

Применение к массиву функции np.any: True

Применение к массиву функции np.all: False


Если необходимо преобразовать массив на основе условия, при этом сохранив его структуру, можно использовать два метода.

* **np.where** - преобразование значений на основе выполнения условия. 

In [19]:
arr1 = np.array([np.array([1,2,3,4,5,6]), np.array([1,2,3,4,5,6])*2, np.array([1,2,3,4,5,6])*3])
print(f'Исходное представление массива: \n{arr1}')
print(f'\nПредставление массива с использованием проверки условия (больше 10) с помощью np.where: \n{np.where(arr1 > 10, arr1, 0)}')

Исходное представление массива: 
[[ 1  2  3  4  5  6]
 [ 2  4  6  8 10 12]
 [ 3  6  9 12 15 18]]

Представление массива с использованием проверки условия (больше 10) с помощью np.where: 
[[ 0  0  0  0  0  0]
 [ 0  0  0  0  0 12]
 [ 0  0  0 12 15 18]]


* умножить матрицу на условие.

In [18]:
arr1 = np.array([np.array([1,2,3,4,5,6]), np.array([1,2,3,4,5,6])*2, np.array([1,2,3,4,5,6])*3])
print(f'Исходное представление массива: \n{arr1}')
print(f'\nПредставление массива с использованием проверки условия (больше 10) с помощью np.where: \n{arr1 * (arr1 > 10)}')

Исходное представление массива: 
[[ 1  2  3  4  5  6]
 [ 2  4  6  8 10 12]
 [ 3  6  9 12 15 18]]

Представление массива с использованием проверки условия (больше 10) с помощью np.where: 
[[ 0  0  0  0  0  0]
 [ 0  0  0  0  0 12]
 [ 0  0  0 12 15 18]]


### Операции сравнения массивов

**np.array_equal** - проверка массивов на равенство. Принимает массивы и проверяет равенство в массивах поэлементно. 

In [111]:
arr1 = np.array([np.array([1,2,3,4,5,6]), np.array([1,2,3,4,5,6])*2, np.array([1,2,3,4,5,6])*3])
arr2 = arr1.copy()

print(f'Исходное представление массивов arr1 и arr2: \n{arr1}')
print(f'\nРезультат сравнения массивов arr1 и arr2: {np.array_equal(arr1, arr2)}')
print(f'Результат сравнения массивов arr1 и arr1 с дополнительной осью: {np.array_equal(arr1, arr1.reshape(3,6,1))}')

Исходное представление массивов arr1 и arr2: 
[[ 1  2  3  4  5  6]
 [ 2  4  6  8 10 12]
 [ 3  6  9 12 15 18]]

Результат сравнения массивов arr1 и arr2: True
Результат сравнения массивов arr1 и arr1 с дополнительной осью: False


**np.intersect1d** - возвращает отсортированный массив уникальных элементов, общих для двух входных массивов.
* assume_unique: Если True, то предполагает, что входные массивы уже уникальны, что ускоряет выполнение.
* return_indices: Если True, то также возвращает индексы элементов в каждом из входных массивов.

In [23]:
arr1 = np.array([2, 2.5, 3.7, 2, 5, 3.5])
arr2 = np.array([2, 3, 5, 2, np.nan, 0])

print(f'Исходное представление первого массива: \n{arr1}')
print(f'\nИсходное представление второго массива: \n{arr2}')
print(f'\nОбщие уникальные элементы: \n{np.intersect1d(arr1, arr2)}')
print(f'\nОбщие уникальные элементы с индексами: \n{np.intersect1d(arr1, arr2, return_indices = True)}')

Исходное представление первого массива: 
[2.  2.5 3.7 2.  5.  3.5]

Исходное представление второго массива: 
[ 2.  3.  5.  2. nan  0.]

Общие уникальные элементы: 
[2. 5.]

Общие уникальные элементы с индексами: 
(array([2., 5.]), array([0, 4], dtype=int64), array([0, 2], dtype=int64))


**np.union1d** - возвращает отсортированный массив уникальных элементов, объединенных из двух входных массивов.

In [27]:
arr1 = np.array([2, 2.5, 3.7, 2, 5, 3.5])
arr2 = np.array([2, 3, 5, 2, np.nan, 0])

print(f'Исходное представление первого массива: \n{arr1}')
print(f'\nИсходное представление второго массива: \n{arr2}')
print(f'\nУникальные элементы объединённых массивов: \n{np.union1d(arr1, arr2)}')

Исходное представление первого массива: 
[2.  2.5 3.7 2.  5.  3.5]

Исходное представление второго массива: 
[ 2.  3.  5.  2. nan  0.]

Уникальные элементы объединённых массивов: 
[0.  2.  2.5 3.  3.5 3.7 5.  nan]


**np.in1d** - принимает на вход два массива. Возвращает булев массив той же формы, что и первый, указывающий, содержатся ли элементы первого массива во втором. 

* invert: Если True, то инвертирует результат, то есть возвращает отсутствие элементов первого массива во втором.

In [30]:
arr1 = np.array([2, 2.5, 3.7, 2, 5, 3.5])
arr2 = np.array([2, 3, 5, 2, np.nan, 0])

print(f'Исходное представление первого массива: \n{arr1}')
print(f'\nИсходное представление второго массива: \n{arr2}')
print(f'\nНаличие элементов 1-го массива по 2-м: \n{np.in1d(arr1, arr2)}')
print(f'\nОтсутствие элементов 1-го массива по 2-м: \n{np.in1d(arr1, arr2, invert = True)}')

Исходное представление первого массива: 
[2.  2.5 3.7 2.  5.  3.5]

Исходное представление второго массива: 
[ 2.  3.  5.  2. nan  0.]

Наличие элементов 1-го массива по 2-м: 
[ True False False  True  True False]

Отсутствие элементов 1-го массива по 2-м: 
[False  True  True False False  True]


**np.setdiff1d** - принимает на вход два массива. Возвращает уникальные элементы, которые есть в первом массиве, но отсутствуют во втором.

* assume_unique: Если True, то предполагает, что входные массивы уже уникальны, что ускоряет выполнение. Также этот аргумент отменяет сортировку элементов при выводе, элементы выводятся в соответствии с порядком исходного массива.

In [33]:
arr1 = np.array([2, 2.5, 3.7, 2, 5, 3.5, 3.5])
arr2 = np.array([2, 3, 5, 2, np.nan, 0])

print(f'Исходное представление первого массива: \n{arr1}')
print(f'\nИсходное представление второго массива: \n{arr2}')
print(f'\nУникальные элементы 1-го массива, которых нет во 2-м: \n{np.setdiff1d(arr1, arr2)}')

Исходное представление первого массива: 
[2.  2.5 3.7 2.  5.  3.5 3.5]

Исходное представление второго массива: 
[ 2.  3.  5.  2. nan  0.]

Уникальные элементы 1-го массива, которых нет во 2-м: 
[2.5 3.5 3.7]


**np.setxor1d** - принимает на вход два массива. Возвращает уникальные элементы, которые есть только в одном из массивов, но отсутствуют в обоих.

* assume_unique: Если True, то предполагает, что входные массивы уже уникальны, что ускоряет выполнение. Также этот аргумент отменяет сортировку элементов при выводе, элементы выводятся в соответствии с порядком исходного массива.

In [35]:
arr1 = np.array([2, 2.5, 3.7, 2, 5, 3.5, 3.5])
arr2 = np.array([2, 3, 5, 2, np.nan, 0])

print(f'Исходное представление первого массива: \n{arr1}')
print(f'\nИсходное представление второго массива: \n{arr2}')
print(f'\nУникальные элементы, которые есть только в одном из массивов: \n{np.setxor1d(arr1, arr2)}')

Исходное представление первого массива: 
[2.  2.5 3.7 2.  5.  3.5 3.5]

Исходное представление второго массива: 
[ 2.  3.  5.  2. nan  0.]

Уникальные элементы, которые есть только в одном из массивов: 
[0.  2.5 3.  3.5 3.7 nan]


### Логические операции

**np.logical_and** - поэлементная проверка двух массивов на совокупную истинность. Возвращает массив с булевыми значениями, соответствующими результату проверки. Любое вещественное число соответствует True, кроме нуля. NaN также соответствует True. 

In [9]:
arr1 = np.array([2, 2.5, 3.7, 2, 5, 3.5])
arr2 = np.array([2, 3, 0, 2, np.nan, 0])

print(f'Исходное представление первого массива: \n{arr1}')
print(f'\nИсходное представление второго массива: \n{arr2}')
print(f'Проверка равенства через logical_and: \n {np.logical_and(arr1, arr2)}')

Исходное представление первого массива: 
[2.  2.5 3.7 2.  5.  3.5]

Исходное представление второго массива: 
[ 2.  3.  0.  2. nan  0.]
Проверка равенства через logical_and: 
 [ True  True False  True  True False]


**np.logical_or** - поэлементная проверка двух массивов на истинность элемента хотя бы в одном из них. Возвращает массив с булевыми значениями, соответствующими результату проверки. Любое вещественное число соответствует True, кроме нуля. NaN также соответствует True. 

In [16]:
arr1 = np.array([2, 2.5, 0, 2, np.nan, 3.5])
arr2 = np.array([2, 3, 0, 2, np.nan, 0])

print(f'Исходное представление первого массива: \n{arr1}')
print(f'\nИсходное представление второго массива: \n{arr2}')
print(f'Проверка через logical_or: \n {np.logical_or(arr1, arr2)}')

Исходное представление первого массива: 
[2.  2.5 0.  2.  nan 3.5]

Исходное представление второго массива: 
[ 2.  3.  0.  2. nan  0.]
Проверка через logical_or: 
 [ True  True False  True  True  True]


**np.logical_xor** - поэлементная проверка двух массивов на истинность элемента **только в одном из них**. Возвращает массив с булевыми значениями, соответствующими результату проверки. Любое вещественное число соответствует True, кроме нуля. NaN также соответствует True. 

In [17]:
arr1 = np.array([2, 2.5, 0, 2, np.nan, 3.5])
arr2 = np.array([np.nan, 3, 0, 2, 0, 0])

print(f'Исходное представление первого массива: \n{arr1}')
print(f'\nИсходное представление второго массива: \n{arr2}')
print(f'Проверка через logical_xor: \n {np.logical_xor(arr1, arr2)}')

Исходное представление первого массива: 
[2.  2.5 0.  2.  nan 3.5]

Исходное представление второго массива: 
[nan  3.  0.  2.  0.  0.]
Проверка через logical_xor: 
 [False False False False  True  True]


**np.logical_not** - проверка элементов массива на ложность. Возвращает массив с булевыми значениями, соответствующими результату проверки. Любое вещественное число соответствует True, кроме нуля. NaN также соответствует True. 

In [19]:
arr1 = np.array([2, 2.5, 0, 2, np.nan, 3.5])

print(f'Исходное представление массива: \n{arr1}')
print(f'Проверка через logical_not: \n {np.logical_not(arr1)}')

Исходное представление массива: 
[2.  2.5 0.  2.  nan 3.5]
Проверка через logical_not: 
 [False False  True False False False]


### Операции с векторами

In [28]:
vec1, vec2 = np.random.randint(0, 10, 10), np.random.randint(0, 10, 10)
print(f'Исходный вектор vec1: \n{vec1}')
print(f'\nИсходный вектор vec2: \n{vec2}')
print(f'\nПоэлементное произведение векторов: \n{vec1 * vec2}')
print(f'\nСкалярное произведение векторов через оператор @: {vec1 @ vec2}')
print(f'\nСкалярное произведение векторов через функцию np.dot: {np.dot(vec1,vec2)}')
print(f'\nСкалярное произведение векторов через функцию np.inner: {np.inner(vec1,vec2)}')
print(f'\nВнешнее произведение векторов через функцию np.outer - матрица из перекрёстных произведений чисел векторов друг на друга: \n{np.outer(vec1,vec2)}')

Исходный вектор vec1: 
[6 2 0 3 0 0 8 6 2 2]

Исходный вектор vec2: 
[0 7 3 3 1 2 6 3 7 1]

Поэлементное произведение векторов: 
[ 0 14  0  9  0  0 48 18 14  2]

Скалярное произведение векторов через оператор @: 105

Скалярное произведение векторов через функцию np.dot: 105

Скалярное произведение векторов через функцию np.inner: 105

Внешнее произведение векторов через функцию np.outer - матрица из перекрёстных произведений чисел векторов друг на друга: 
[[ 0 42 18 18  6 12 36 18 42  6]
 [ 0 14  6  6  2  4 12  6 14  2]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0 21  9  9  3  6 18  9 21  3]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0 56 24 24  8 16 48 24 56  8]
 [ 0 42 18 18  6 12 36 18 42  6]
 [ 0 14  6  6  2  4 12  6 14  2]
 [ 0 14  6  6  2  4 12  6 14  2]]


### Операции между матрицей и вектором

В *Numpy* не различается вектор-строка и вектор-столбец. Их произведение будет одинаковым независимо от расположения друг относительно друга в операции произведения. Для произведения векторов используется функция **np.dot** или **оператор @**.

In [30]:
vec1 = np.random.randint(0, 10, [1, 10])
vec2 = np.random.randint(0, 10, [10, 1])

print(f'Исходный вектор vec1: \n{vec1}')
print(f'\nИсходный вектор vec2: \n{vec2}')
print(f'\nПроизведение vec1 * vec2: \n{vec1 * vec2}')
print(f'\nПроизведение vec2 * vec1: \n{vec2 * vec1}')

Исходный вектор vec1: 
[[1 6 3 2 1 6 5 5 5 7]]

Исходный вектор vec2: 
[[9]
 [8]
 [9]
 [9]
 [1]
 [8]
 [8]
 [8]
 [4]
 [4]]

Произведение vec1 * vec2: 
[[ 9 54 27 18  9 54 45 45 45 63]
 [ 8 48 24 16  8 48 40 40 40 56]
 [ 9 54 27 18  9 54 45 45 45 63]
 [ 9 54 27 18  9 54 45 45 45 63]
 [ 1  6  3  2  1  6  5  5  5  7]
 [ 8 48 24 16  8 48 40 40 40 56]
 [ 8 48 24 16  8 48 40 40 40 56]
 [ 8 48 24 16  8 48 40 40 40 56]
 [ 4 24 12  8  4 24 20 20 20 28]
 [ 4 24 12  8  4 24 20 20 20 28]]

Произведение vec2 * vec1: 
[[ 9 54 27 18  9 54 45 45 45 63]
 [ 8 48 24 16  8 48 40 40 40 56]
 [ 9 54 27 18  9 54 45 45 45 63]
 [ 9 54 27 18  9 54 45 45 45 63]
 [ 1  6  3  2  1  6  5  5  5  7]
 [ 8 48 24 16  8 48 40 40 40 56]
 [ 8 48 24 16  8 48 40 40 40 56]
 [ 8 48 24 16  8 48 40 40 40 56]
 [ 4 24 12  8  4 24 20 20 20 28]
 [ 4 24 12  8  4 24 20 20 20 28]]


Произведение матриц на вектор или на другую матрицу может быть осуществлено без ошибок только с помощью специальных функций: **np.dot** , **np.matmul** или **оператора @**.

In [3]:
mx1 = np.random.randint(0, 10, [2, 10])
mx2 = np.random.randint(0, 10, [10, 2])

print(f'Исходная матрица mx1: \n{mx1}')
print(f'\nИсходная матрица mx2: \n{mx2}')
print(f'\nПроизведение mx1 * mx2 через функцию np.dot: \n{np.dot(mx1, mx2)}')
print(f'\nПроизведение mx2 * mx1 через функцию np.dot: \n{np.dot(mx2, mx1)}')
print(f'\nПроизведение mx1 * mx2 через функцию np.matmul: \n{np.matmul(mx1, mx2)}')
print(f'\nПроизведение mx2 * mx1 через функцию np.matmul: \n{np.matmul(mx2, mx1)}')

Исходная матрица mx1: 
[[4 9 8 0 4 8 9 7 0 9]
 [4 7 3 3 3 2 9 3 7 4]]

Исходная матрица mx2: 
[[0 4]
 [2 6]
 [7 0]
 [3 4]
 [2 4]
 [6 4]
 [8 2]
 [8 7]
 [2 8]
 [5 6]]

Произведение mx1 * mx2 через функцию np.dot: 
[[303 239]
 [192 209]]

Произведение mx2 * mx1 через функцию np.dot: 
[[ 16  28  12  12  12   8  36  12  28  16]
 [ 32  60  34  18  26  28  72  32  42  42]
 [ 28  63  56   0  28  56  63  49   0  63]
 [ 28  55  36  12  24  32  63  33  28  43]
 [ 24  46  28  12  20  24  54  26  28  34]
 [ 40  82  60  12  36  56  90  54  28  70]
 [ 40  86  70   6  38  68  90  62  14  80]
 [ 60 121  85  21  53  78 135  77  49 100]
 [ 40  74  40  24  32  32  90  38  56  50]
 [ 44  87  58  18  38  52  99  53  42  69]]

Произведение mx1 * mx2 через функцию np.matmul: 
[[303 239]
 [192 209]]

Произведение mx2 * mx1 через функцию np.matmul: 
[[ 16  28  12  12  12   8  36  12  28  16]
 [ 32  60  34  18  26  28  72  32  42  42]
 [ 28  63  56   0  28  56  63  49   0  63]
 [ 28  55  36  12  24  32  63  33  

**np.trace** - "след" матрицы, т.е. сумма всех элементов, лежащих на главной диагонали матрицы. 

In [36]:
mx = np.random.randint(0, 10, [2, 2])

print(f'Исходная матрица mx: \n{mx}')
print(f'\nСлед матрицы: {np.trace(mx)}')

Исходная матрица mx: 
[[5 4]
 [9 5]]

След матрицы: 10


**np.outer** - внешнее произведение матриц (перекрёстное произведение элементов матрицы друг на друга. Порядок расположения матриц при произведении имеет значение для результата, но один результат приводится к другому также и с помощью транспонирования.

In [47]:
mx1 = np.random.randint(0, 10, [2, 2])
mx2 = np.random.randint(0, 10, [2, 2])

print(f'Исходная матрица mx1: \n{mx1}')
print(f'\nИсходная матрица mx2: \n{mx2}')
print(f'\nВнешнее произведение mx1 * mx2: \n{np.outer(mx1, mx2)}')
print(f'\nВнешнее произведение mx2 * mx1: \n{np.outer(mx2, mx1)}')

Исходная матрица mx1: 
[[8 6]
 [4 6]]

Исходная матрица mx2: 
[[3 4]
 [9 8]]

Внешнее произведение mx1 * mx2: 
[[24 32 72 64]
 [18 24 54 48]
 [12 16 36 32]
 [18 24 54 48]]

Внешнее произведение mx2 * mx1: 
[[24 18 12 18]
 [32 24 16 24]
 [72 54 36 54]
 [64 48 32 48]]


**np.transpose** - транспонирование матрицы. 

In [52]:
mx = np.random.randint(0, 10, [2, 2])

print(f'Исходная матрица mx: \n{mx}')
print(f'\nТранспонированная матрица mx: \n{np.transpose(mx)}')

Исходная матрица mx: 
[[7 7]
 [2 1]]

Транспонированная матрица mx: 
[[7 2]
 [7 1]]


**np.array.T** - альтернативный метод транспонирования. 

**np.swapaxes** - метод для перемещения мест осей массива. Первый аргументом принимает массив, вторым (axis1) - ось, которую нужно поменять местами с axis2, третьим (axis2) - ось, которую нужно поменять местами с axis1.

In [10]:
mx = np.random.randint(0, 10, [2, 3, 4])

print(f'Исходная матрица mx: \n{mx}')
print(f'\nРазмерность исходной матрицы: \n{mx.shape}')

print(f'\nНовая матрица после замены осей 1 и 2: \n{np.swapaxes(mx, 1, 2)}')
print(f'\nРазмерность матрицы после замены осей: \n{np.swapaxes(mx, 1, 2).shape}')

Исходная матрица mx: 
[[[4 1 1 3]
  [7 2 0 8]
  [2 7 2 9]]

 [[5 1 2 9]
  [8 3 4 9]
  [8 7 1 9]]]

Размерность исходной матрицы: 
(2, 3, 4)

Новая матрица после замены осей 1 и 2: 
[[[4 7 2]
  [1 2 7]
  [1 0 2]
  [3 8 9]]

 [[5 8 8]
  [1 3 7]
  [2 4 1]
  [9 9 9]]]

Размерность матрицы после замены осей: 
(2, 4, 3)
